"""Canonical cross-layer contracts for the Qwen3-TTS engine."""

from nari_qwen3_tts.contract.codec_state import IncrementalCodecState
from nari_qwen3_tts.contract.command import (
    AppendText,
    CancelRequest,
    EngineCommand,
    StopEngine,
    SubmitRequest,
)
from nari_qwen3_tts.contract.errors import (
    BackpressureExceeded,
    LiveInputClosedError,
    RequestCancelled,
    RequestRejected,
    ServiceCapacityExceeded,
    ServiceUnavailable,
    StreamingTextControlTokenError,
    SynthesisError,
)
from nari_qwen3_tts.contract.health import (
    EngineHealth,
    ReadinessStatus,
    ServicePhase,
    StageStats,
    evaluate_readiness,
)
from nari_qwen3_tts.contract.model import (
    FileDigest,
    ModelArtifactIdentity,
    ModelIdentityPolicy,
    SynthesisModelSpec,
)
from nari_qwen3_tts.contract.request import (
    AdmittedRequest,
    EncodedText,
    FragmentTokenization,
    SynthesisRequest,
    TalkerPrompt,
    TextContinuation,
    TextFrontend,
)
from nari_qwen3_tts.contract.result import (
    CodecStateDelta,
    CodePredictorStateDelta,
    KVPublication,
    RequestStateDelta,
    StageBatchRowResult,
    StageExecutionCompletion,
    TalkerStateDelta,
)
from nari_qwen3_tts.contract.stage import (
    CodecCaptureKey,
    CodecExecutionMode,
    CodePredictorCaptureKey,
    CudaGraphKey,
    CudaGraphRef,
    RequestLane,
    SynthesisStage,
    TalkerDecodeCaptureKey,
    TalkerPrefillCaptureKey,
)
from nari_qwen3_tts.contract.stream import PCMStream
from nari_qwen3_tts.contract.work import (
    TALKER_DECODE_COMPATIBILITY,
    CodecBatchCompatibility,
    CodePredictorBatchCompatibility,
    ReadyStageWork,
    ScheduleDecision,
    StageBatchCompatibility,
    StageBatchRow,
    StageExecutionBatch,
    TalkerDecodeBatchCompatibility,
    TalkerPrefillBatchCompatibility,
    codec_batch_compatible,
)

__all__ = [
    "AdmittedRequest",
    "AppendText",
    "BackpressureExceeded",
    "CodecCaptureKey",
    "CancelRequest",
    "CodecStateDelta",
    "CodecExecutionMode",
    "CodePredictorCaptureKey",
    "CodePredictorStateDelta",
    "CudaGraphKey",
    "CudaGraphRef",
    "EncodedText",
    "EngineHealth",
    "EngineCommand",
    "FragmentTokenization",
    "FileDigest",
    "IncrementalCodecState",
    "KVPublication",
    "LiveInputClosedError",
    "ModelArtifactIdentity",
    "ModelIdentityPolicy",
    "PCMStream",
    "RequestCancelled",
    "RequestRejected",
    "RequestLane",
    "RequestStateDelta",
    "ReadyStageWork",
    "ReadinessStatus",
    "ScheduleDecision",
    "ServiceCapacityExceeded",
    "ServicePhase",
    "ServiceUnavailable",
    "SynthesisError",
    "StageBatchCompatibility",
    "StageBatchRow",
    "StageBatchRowResult",
    "StageExecutionBatch",
    "StageExecutionCompletion",
    "StageStats",
    "StreamingTextControlTokenError",
    "StopEngine",
    "SubmitRequest",
    "SynthesisModelSpec",
    "SynthesisRequest",
    "SynthesisStage",
    "TalkerPrompt",
    "TalkerStateDelta",
    "TalkerDecodeCaptureKey",
    "TalkerDecodeBatchCompatibility",
    "TALKER_DECODE_COMPATIBILITY",
    "TalkerPrefillBatchCompatibility",
    "TalkerPrefillCaptureKey",
    "TextFrontend",
    "TextContinuation",
    "CodePredictorBatchCompatibility",
    "CodecBatchCompatibility",
    "codec_batch_compatible",
    "evaluate_readiness",
]
